name: ingredient_collector_parser_sample
description: Sample parser for the ingredient_collector repo.
version: 1.0.0

environment:
  sdk: ^3.0.2

dependencies:
  html: ^0.15.1
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
